### ISSUE TITLE
Error downloading installer binary on S6000-ON

### ISSUE THREAD

**Issue by sm1988** [open-switch/opx-docs#1]
Hi!

I Just tried to use this link on my Dell S6000-ON 

ONIE:~ # onie-nos-install https://dell-networking.bintray.com/opx-images/opx-onie-installer/1.0/onie-installer-x86_64.bin
Info: Fetching https://dell-networking.bintray.com/opx-images/opx-onie-installer/1.0/onie-installer-x86_64.bin ...
wget: not an http or ftp url: https://dell-networking.bintray.com/opx-images/opx-onie-installer/1.0/onie-installer-x86_64.bin

Is this a correct link? Also, I tried to install an X86_64 installer image but I don't see one in docker container. 

root@2a31a585d39f:/mnt# ls -l | grep opx | wc -l
170
root@2a31a585d39f:/mnt# ls -l | grep opx-dell   
-rw-r--r--  1 root root     1296 Mar  1 06:33 opx-dell-s6000_1.0.3_all.deb
-rw-r--r--  1 root root     1286 Mar  1 06:33 opx-dell-vm_1.0.3_all.deb

Which of these files can be used from ONIE.

Thanks,
Shishir

**Comment by c-wichmann** [comment]
Sorry Shishir,

The documentation is fixed now.

The correct path is:
https://dell-networking.bintray.com/opx-images/opx-onie-installer_1.1_amd64.bin


An update was made to the installer path recently and the documentation update had not been completed.
