### ISSUE TITLE
Install OPX on system via apt get commands not linked from main page

### ISSUE THREAD

**Issue by c-wichmann** [open-switch/opx-docs#11]
A link https://github.com/open-switch/opx-docs/wiki/Install-OPX-Base-on-Dell-S6000-ON-platform is missing.

**Comment by amybuck** [comment]
Dell - Internal Use - Confidential

The correct link is https://github.com/open-switch/opx-docs/wiki/Install-OPX-Base-on-Dell-EMC-ON-series-platforms :)

Amy Buck
Technical Content Developer 3 | Dell Champion<https://inside.dell.com/groups/dell-champions/overview>
Dell EMC | Information Design & Development
Follow me on @AmybAtDell / @abucksocial / @OpenSwitchOPX / @OpenSwitchNOS
