### ISSUE TITLE
Unable to ssh to open switch vm

### ISSUE THREAD

**Issue by shravyarani** [open-switch/opx-docs#14]
Installed open switch  vm on mac as per instructions provided in the wiki:
It creates a vm but says:
Setup complete! You can now connect using: ssh -p 2223 opxUser@127.0.0.1
Failed to execute script vm

<img width="695" alt="screen shot 2018-04-25 at 5 22 53 pm" src="https://user-images.githubusercontent.com/6436711/39279353-5bf02860-48ad-11e8-9e29-f8084ad7b249.png">

I am unable to ssh to it.

And after the installation, I see vm started in virtual box but its asking me username and password to login though I haven't provided any.

<img width="353" alt="opxlogin" src="https://user-images.githubusercontent.com/6436711/39279326-29397b06-48ad-11e8-8315-62382cdd49d6.png">

**Comment by jeff-yin** [comment]
Hi, try admin/admin for username/PW. Docs may need to be updated here...

On Apr 25, 2018, at 17:22, shravyarani <notifications@github.com<mailto:notifications@github.com>> wrote:


Installed open switch vm on mac as per instructions provided in the wiki:
It creates a vm but says:
Setup complete! You can now connect using: ssh -p 2223 opxUser@127.0.0.1<mailto:opxUser@127.0.0.1>
Failed to execute script vm

[opx1]<https://user-images.githubusercontent.com/6436711/39279265-c5d42d2c-48ac-11e8-9039-111c7ae64f4e.png>

I am unable to ssh to it.

And after the installation, I see vm started in virtual box but its asking me username and password to login though I haven't provided any.

[opxlogin]<https://user-images.githubusercontent.com/6436711/39279326-29397b06-48ad-11e8-8315-62382cdd49d6.png>

**Comment by jghalam** [comment]
Can you share the command you executed please? Also, by looking at the output you have included, looks like you have other VMs running. Could you please run “mvm list” command and send me the output?
