### ISSUE TITLE
Unable to ssh opx vms through vagrant

### ISSUE THREAD

**Issue by shravyarani** [open-switch/opx-docs#15]
I have a use case to create 3 opx vms and I should be able to ping from one vm to other. 
Below is my Vagrantfile:

BOX_IMAGE="opx/2.3.0"
BOX_VERSION="2.3.0"
SWITCH_COUNT=3
Vagrant.configure("2") do |config|
  (1..SWITCH_COUNT).each do |i|
        config.vm.define "switch#{i}" do |subconfig|
                subconfig.vm.box = BOX_IMAGE
                subconfig.vm.box_version = BOX_VERSION
                subconfig.vm.hostname = "switch#{i}"
                subconfig.vm.network "private_network", ip: "10.0.0.#{i + 10}"
        end
  end
  # call shell scripts
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
  SHELL
end

When I'm trying to do vagrant up it fails with the below error:

Bringing machine 'switch1' up with 'virtualbox' provider...
Bringing machine 'switch2' up with 'virtualbox' provider...
Bringing machine 'switch3' up with 'virtualbox' provider...
==> switch1: Checking if box 'opx/2.3.0' is up to date...
==> switch1: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

My vagrant ssh-config:

Host switch1
  HostName 127.0.0.1
  User vagrant
  Port 2202
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/sthatipally/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

Can someone please help me to figure out why ssh is failing?

**Comment by michaelsiuda** [comment]
Hi @shravyarani , 

Does your setup work if you don't specify the private network?

If yes, the problem may be related to the way how the OPX VM maps network adapters to interfaces (see https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine#setup-vm-network-adapters). What you may be seeing is that e101-001-0 instead of eth0 is being attached to the management network.

You can solve this by making sure that the management interface has correct adapter type.

This is an example config that I've been using with vagrant and virtualbox:
```
subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
        vb.customize ["modifyvm", :id, "--macaddress1", "0800275f0200"]
        vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
        vb.customize ["modifyvm", :id, "--macaddress2", "0800275f0201"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--nictype3", "Am79C973"]
        vb.customize ["modifyvm", :id, "--macaddress3", "0800275f0205"]
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
end
```

Note that apart from the NIC type you also have to make sure that MAC addresses follow OPX VM's convention - e101-001-0 has MAC of eth0 + 1, and then e101-N-0 has MAC address of e101-(N-1)-0 + 4.

Hope this helps.

Michael

**Comment by shravyarani** [comment]
@michaelsiuda yes, it works without private network and shell commands but if I give private network it doesn't.

**Comment by shravyarani** [comment]
@madhu222 my virtual box version is 5.2.8. I did try Vagrant::Config.run do |config| config.ssh.forward_agent = true end. It didn't work.

**Comment by michaelsiuda** [comment]
@shravyarani You can use the config example I pasted above.  Merging with the config you mentioned above, it would looks something like this:

```
BOX_IMAGE="opx/2.3.0"
BOX_VERSION="2.3.0"
SWITCH_COUNT=3

Vagrant.configure("2") do |config|
    (1..SWITCH_COUNT).each do |i|
    config.vm.define "switch#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.box_version = BOX_VERSION
        subconfig.vm.hostname = "switch#{i}"
# Here is the network adapter config
        subconfig.vm.provider "virtualbox" do |vb|
            # eth0 
            vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
            vb.customize ["modifyvm", :id, "--macaddress1", "0800275f0200"]
            # e101-001-0
            vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
            vb.customize ["modifyvm", :id, "--macaddress2", "0800275f0201"]
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        end
#####
        subconfig.vm.network "private_network", ip: "10.0.0.#{i + 10}"
    end
end
```

Let me know if it works.

**Comment by shravyarani** [comment]
@michaelsiuda, it doesn't. I see below error: 

==> switch3: Attempting graceful shutdown of VM...
==> switch2: Attempting graceful shutdown of VM...
==> switch1: Attempting graceful shutdown of VM...
sthatipally-a01:opxVagrant sthatipally$ vagrant up
Bringing machine 'switch1' up with 'virtualbox' provider...
Bringing machine 'switch2' up with 'virtualbox' provider...
Bringing machine 'switch3' up with 'virtualbox' provider...
==> switch1: Checking if box 'opx/2.3.0' is up to date...
==> switch1: Clearing any previously set forwarded ports...
==> switch1: Clearing any previously set network interfaces...
==> switch1: Preparing network interfaces based on configuration...
    switch1: Adapter 1: nat
    switch1: Adapter 2: hostonly
==> switch1: Forwarding ports...
    switch1: 22 (guest) => 2222 (host) (adapter 1)
==> switch1: Running 'pre-boot' VM customizations...
==> switch1: Booting VM...
==> switch1: Waiting for machine to boot. This may take a few minutes...
    switch1: SSH address: 127.0.0.1:2222
    switch1: SSH username: vagrant
    switch1: SSH auth method: private key
==> switch1: Machine booted and ready!
==> switch1: Checking for guest additions in VM...
    switch1: The guest additions on this VM do not match the installed version of
    switch1: VirtualBox! In most cases this is fine, but in rare cases it can
    switch1: prevent things such as shared folders from working properly. If you see
    switch1: shared folder errors, please make sure the guest additions within the
    switch1: virtual machine match the version of VirtualBox you have installed on
    switch1: your host and reload your VM.
    switch1: 
    switch1: Guest Additions Version: 5.1.14
    switch1: VirtualBox Version: 5.2
==> switch1: Setting hostname...
==> switch1: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown '' || true
/sbin/ip addr flush dev ''
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post
cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces
rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup ''

Stdout from the command:



Stderr from the command:

/sbin/ifdown: interface  not configured
Usage: ip addr {add|change|replace} IFADDR dev STRING [ LIFETIME ]
                                                      [ CONFFLAG-LIST ]
       ip addr del IFADDR dev STRING [mngtmpaddr]
       ip addr {show|save|flush} [ dev STRING ] [ scope SCOPE-ID ]
                            [ to PREFIX ] [ FLAG-LIST ] [ label PATTERN ] [up]
       ip addr {showdump|restore}
IFADDR := PREFIX | ADDR peer PREFIX
          [ broadcast ADDR ] [ anycast ADDR ]
          [ label STRING ] [ scope SCOPE-ID ]
SCOPE-ID := [ host | link | global | NUMBER ]
FLAG-LIST := [ FLAG-LIST ] FLAG
FLAG  := [ permanent | dynamic | secondary | primary |
           tentative | deprecated | dadfailed | temporary |
           CONFFLAG-LIST ]
CONFFLAG-LIST := [ CONFFLAG-LIST ] CONFFLAG
CONFFLAG  := [ home | nodad | mngtmpaddr | noprefixroute ]
LIFETIME := [ valid_lft LFT ] [ preferred_lft LFT ]
LFT := forever | SECONDS
/etc/network/interfaces:10: too few parameters for iface line
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"

**Comment by michaelsiuda** [comment]
Sorry @shravyarani but I can't tell why it failed for you.  My only bet is that vagrant somehow managed to corrupt the /etc/network/interfaces file on the VM.  I would try destroying the VMs and recreating them again with the new Vagrantfile, rather going through a reload process.

However, it's worth saying at this point that I'm not part of the OPX team, but just trying to help.  Maybe @madhu222 should also have a look?

**Comment by shravyarani** [comment]
@michaelsiuda Thanks alot for the help, I tried destroying vm's and ran again but it still fails. When I remove **subconfig.vm.network "private_network", ip: "10.0.0.#{i + 10}"** this line it works but with it doesn't. But I want to create a vm's such that I can ping to one from another vm.
Is there any other way to acheive this?

**Comment by shravyarani** [comment]
@madhu222 , @michaelsiuda  Is there a command to manually set an ip address on eth0 port? Ifconfig doesn't work for me

**Comment by jeff-yin** [comment]
@shravyarani sorry for the lack of follow-up on my end. Any updates to your troubleshooting efforts?

**Comment by shravyarani** [comment]
I fixed it thanks
