### ISSUE TITLE
Unable to create opx vms

### ISSUE THREAD

**Issue by pspk01** [open-switch/opx-docs#17]
I am unable to create opx switch
Command: ./mvm create switch1 --port 8089

             t8.                           ..S:.            
          .;.88X                            ;888:           
        X; 8. 8X                            t888S 8X        
    .8S;;.:.  8X...                        .;@@8@8@8X88..   
  .@ :.       :::::.                 .  8XSS88S8888@@@8:@   
@8S:..       ..    : @                S 88X@8@88888888@88 88
8t X               ..; @           .S 8888S8@88@@888X8888888
  .X8X        t@ @  .::X.          888X8S88888888888X@88:   
     S  8    .@t 8 ;:.  : X.    .S 8S888888St8S888888S :    
        :@8X:.8X   @ ;:.tX8    S 88X8888;;; X88888XX       
            @.@t     :SX:.    888X8888    .. 88@:.          
             :X:      88.   SS@S88888:      t8X.            
                          X 888X888S:      .:.              
                         888S8S888;                         
                       SX@X888888X            .             
           .t8.:     S 8888X88XX: .88:8.    ;8 8.           
         .X:88XX..  888X8S88      .;SX8:    X8@888.         
      .SSX888X8.  X 8X8888@      8X   .X 8 .t8 .:@:X8:      
   :8.8X88X8@88;8X@88888@      .:;8 t...tS X.@   .:tX8XXt   
 :X8S@88XX8888888@888X88            tX ...t;.         .;8tt 
88X888@88X@88888888888@.             8 ;:..               X:
 :X8888@8S@8@8888888.:.                @ @888.        .8X;t 
  ;. SS888888@8@t  ; ..                   ..X8       S.:    
     .::8888888  ..                         X8   :X8@;      
      .:; .S888S:                           X8S :X.         
          :;  8X.                           ;.X             
           ..::         

    _____                  _____          _ _       _     
   |  _  |                /  ___|        (_) |     | |    
   | | | |_ __   ___ _ __ \ `--.__      ___| |_ ___| |__  
   | | | | '_ \ / _ \ '_ \ `--. \ \ /\ / / | __/ __| '_ \ 
   \ \_/ / |_) |  __/ | | /\__/ /\ V  V /| | || (__| | | |
    \___/| .__/ \___|_| |_\____/  \_/\_/ |_|\__\___|_| |_|
         | |                                              
         |_|    

                        Version 2.3.2        
                                       
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files on the virtual machine in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

https://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-installer-x86_64.bin seems to point to an invalid binary.
Failed to execute script vm

**Comment by jghalam** [comment]
It appears the link to the stable installer has changed. Please try again with the following option:

./mvm create switch1 —port 8089 —bin https://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin <https://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin>

Thanks,
Joe

**Comment by pspk01** [comment]
Thanks that worked but now I see some other issue:
I am trying to install vim and i see this when I do update
root@open_vm:~# apt-get update
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://httpredir.debian.org jessie InRelease
  
Err http://httpredir.debian.org jessie-backports InRelease
  
Err http://httpredir.debian.org jessie-updates InRelease
  
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-backports Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://deb.openswitch.net testing InRelease
  
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://deb.openswitch.net stable InRelease
  
Err http://deb.openswitch.net 2-updates InRelease
  
Err http://deb.openswitch.net testing Release.gpg
  Could not resolve 'deb.openswitch.net'
Err http://deb.openswitch.net stable Release.gpg
  Could not resolve 'deb.openswitch.net'
Err http://deb.openswitch.net 2-updates Release.gpg
  Could not resolve 'deb.openswitch.net'
Reading package lists... Done
W: Failed to fetch http://deb.openswitch.net/jessie/dists/testing/InRelease  

W: Failed to fetch http://deb.openswitch.net/contrib/dists/stable/InRelease  

W: Failed to fetch http://deb.openswitch.net/jessie/dists/2-updates/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://deb.openswitch.net/jessie/dists/testing/Release.gpg  Could not resolve 'deb.openswitch.net'

W: Failed to fetch http://deb.openswitch.net/contrib/dists/stable/Release.gpg  Could not resolve 'deb.openswitch.net'

W: Failed to fetch http://deb.openswitch.net/jessie/dists/2-updates/Release.gpg  Could not resolve 'deb.openswitch.net'

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by 8888888** [comment]
Not sure why I'm on this, and I suspect the expected recipient is not me.
Please drop my email address from this thread and reach out to whomever
you're trying to communicate with via either another address or another
method. No reply requested or desired.

**Comment by jeff-yin** [comment]
@pspk01 any update? Was the issue related to your network?

**Comment by jeff-yin** [comment]
Closing the issue due to lack of update.
