### ISSUE TITLE
Where to download open-switch vmdk from?

### ISSUE THREAD

**Issue by shravyarani** [open-switch/opx-docs#18]
Hi All,

I want to run open-switch vm on QEMU, where should I download required vmdk from?

Thanks.

**Comment by jeff-yin** [comment]
@mikelazar -- I vaguely recall you presenting something about QEMU a while ago, although AFAIK this isn't something supported by OpenSwitch (correct me if I'm wrong)

**Comment by mujtabaali22** [comment]
@mikelazar ... I also need to know if I can run an openswitch image on Qemu?
here is a link which hints it but i am not sure if it works or not. 
https://brezular.com/2017/02/18/openswitch-network-operating-system/

**Comment by jeff-yin** [comment]
Try this updated guide. I know it's 
https://brezular.com/2018/09/17/openswitch-opx-3-0-0-installation-on-ubuntu-18-04-1-lts/
