### ISSUE TITLE
Broken link for OSX vm tool

### ISSUE THREAD

**Issue by pranasblk** [open-switch/opx-docs#19]
[https://archive.openswitch.net/vm-tools/mvm](https://archive.openswitch.net/vm-tools/mvm)

**Comment by pranasblk** [comment]
Would it be possible to provide instructions how to get artefacts from sources instead of executable binary blobs?

**Comment by pranasblk** [comment]
After some hours of trying got the binary, but another binary is not accessible? Would you mind publishing them via e.g. torrent network?
`Getting OS-Installer via URL. Downloading.... Please wait!
Failed to get file https://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-installer-x86_64.bin: [Errno socket error] [Errno 60] Operation timed out`

**Comment by jghalam** [comment]
The URL has been moved, and we need to modify the default one. You can run the command with “—-bin” option with the following link:
http://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin <http://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin>

So, it should work if you run it something like this:

$ lvm create OPX_VM —-bin http://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin <http://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-jessie-installer-x86_64.bin>

Joe

**Comment by jeff-yin** [comment]
Joe's suggestion above should work. Please reopen the issue if you are still facing difficulties.
