### ISSUE TITLE
docker-opx not found

### ISSUE THREAD

**Issue by larryming** [open-switch/opx-docs#2]
Hi,
When I run " sudo ./opx_setup" command, it report docker-opx image not found, and I also can not find the image from the web("https://index.docker.io/v1/repositories/library/docker-opx/images").

Unable to find image 'docker-opx:base' locally
Pulling repository docker.io/library/docker-opx
docker: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/docker-opx/images. You may want to check your internet connection or if you are behind a proxy..
See 'docker run --help'.
cat: id: No such file or directory
Error response from daemon: No such container: docker-opx:latest
cat: id: No such file or directory
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

**Comment by c-wichmann** [comment]
Hi,

Did you setup your Ubuntu system with the setup in this page?
https://github.com/open-switch/opx-build

Seems like you did but just checking.  When running opx_setup you need to be in the opx-build/scripts directory. 

The docker image is created in opx-build/scripts/opx_setup - using the docker file that is in the same directory.

You can also join the chat.openswitch.net where we can also interactively help troubleshoot

**Comment by larryming** [comment]
OK, thank you.
