### ISSUE TITLE
switch configuration for bridging or routing by Linux commands

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-docs#20]
Does Linux commands (like brctl addbr, or ip route) will let the underlying switch silicon perform bridging or routing ? How can  OPX help it ?

Thanks.

**Comment by atanu-mandal** [comment]
Hi @jimmymagemtek , yes,OPX would propagate the information configured through Linux utilities like brctl addbr, ip route  to underlying switch silicon. There is few restrictions like bridge (i.e. vlan) has to have one tagged port to be programmed into NPU.

e,g. below configuration will program the NPU with VLAN 100 (e101-001-0 as tagged member)

brctl addbr br100

ip addr flush dev e101-001-0 

ip link add link e101-001-0 name e101-001-0.100 type vlan id 100

brctl addif br100 e101-001-0.100

Thanks,
-Atanu

**Comment by q2dg** [comment]
Current configuration guide (http://archive.openswitch.net/docs/3.0.0/openswitch_opx_300_config_guide.pdf) shows the use of ifconfig command. Maybe you could consider its deprecation state.
Moreover, you could consider replacing  brctl command (which is deprecated, too, at least in Fedora)  by bridge command (from iproute suite) 
Thanks

**Comment by jeff-yin** [comment]
Opened #25 to track this.
