### ISSUE TITLE
Invalid links in wiki-article "Run virtual machine"

### ISSUE THREAD

**Issue by HolyShitMan** [open-switch/opx-docs#21]
Links to [https://archive.openswitch.net/](https://archive.openswitch.net/) (vm.exe, lvm and mvm)  do not work because archive.openswitch.net does not support HTTPS.

Therefore all links should be converted to HTTP ->  [http://archive.openswitch.net/](http://archive.openswitch.net/)

**Comment by amybuck** [comment]
All links from openswitch.net have always been http://archive.openswitch.net. I do not control the links from within archive.openswitch.net.

**Comment by jeff-yin** [comment]
@amybuck -- this issue was talking about links in opx-docs/wiki. Anyway, I fixed them in the latest edit to this page:
https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine
