### ISSUE TITLE
Will it work with other dell emc switches not listed in the supported list?

### ISSUE THREAD

**Issue by McFlat** [open-switch/opx-docs#24]
Nice stuff you got here with OPX, but will it work with DELL EMC switches I can actually find on Amazon or NewEgg or TigerDirect? The ones in the supported hardware list I'm having difficulty finding and perhaps even if I did find one by chance it would be out of my budget.

https://www.amazon.com/Dell-EMC-Networking-N1148P-ON-Switch/dp/B077BCDW9T/

I'm looking to run something custom instead of my current setup, OPX seems to be a great fit for what I'm trying to do since the netgear software kinda sucks. I want to be able to customize the software and fix bugs too.
XS728T ProSAFE 28-Port 10-Gigabit L2+ Smart Switch

**Comment by jghalam** [comment]
Hi,
We have ported support for the listed platforms only. But, we continue to bring more and more platforms onboard. The switch you included in the link is one of those that it is not currently supported.

If you have a specific switch that you want to work with or you think it’s similar to those supported, don’t hesitate to reach out and get some help.
cheers,
Joe

**Comment by jeff-yin** [comment]
Joe’s answer above is correct. The OPX project currently supports platforms with Intel-based CPUs and networking ASICs with vendor support for the Switch Abstraction Interface API. The N1148P, while it does support ONIE, lacks the requisite CPU and ASIC support in OPX. 

For your port count needs (but not necessarily your budget), I’d look at the Dell EMC S4100 series like the S4128T or S4112T. These are supported by OPX. 

Closing the issue for now, but feel free to re-open it and ask any follow up questions.
