### ISSUE TITLE
OpenFlow in OPX?

### ISSUE THREAD

**Issue by grantcurell** [open-switch/opx-docs#28]
I've been trying to figure this out, but couldn't find a good source, does OPX support OpenFlow?

**Comment by atanu-mandal** [comment]
HI @grantcurell , OPX does not have any OpenFlow agent yet.

**Comment by jeff-yin** [comment]
@grantcurell -- To add, this is a potential roadmap item where the OPX project would welcome community involvement. OPX certainly provides the APIs to support an OpenFlow agent. If you'd like to get involved, please get in touch.
