### ISSUE TITLE
3.2.0 Upgrade issue

### ISSUE THREAD

**Issue by alejandroed** [open-switch/opx-docs#29]
Hi! 

I'm doing a fresh install in a DELL Z9100-ON with the 3.2.0 image and after the first login if I do a "apt upgrade" the system hangs during the apt in:

Setting up opx-platform-config-dell-z9100 (1.8.1) ...

It seems that dpkg is not consuming resources:

root@OPX:/home/admin# ps aux |grep dpkg
root      7826  0.0  0.0  16736  3748 pts/1    Ss+  10:07   0:00 /usr/bin/dpkg --status-fd 38 --configure --pending
root     13716  0.0  0.0   4276  1420 pts/1    S+   10:07   0:00 /bin/sh /var/lib/dpkg/info/opx-platform-config-dell-z9100.postinst configure 1.8.0+git20190618.b964d8a

If I stop manually the apt process (CTRL+c) and try to install the opx-platform-config-dell-z9100_1.8.1_all.deb package manually the result is the same:

root@OPX:/var# dpkg -i opx-platform-config-dell-z9100_1.8.1_all.deb
(Reading database ... 29435 files and directories currently installed.)
Preparing to unpack opx-platform-config-dell-z9100_1.8.1_all.deb ...

**Comment by gunasekaran-t** [comment]
Dist upgrade seems to try to restart opx-platform-init service which seems to get stuck. Ideally it should only be started during bootup. Disabling the service and doing dist-upgrade works fine. 
Follow the steps below until the fix comes. 

```
systemctl disable opx-platform-init
apt-get dist-upgrade
systemctl enable opx-platform-init
reboot
```

**Comment by mikelazar** [comment]
Assuming that this is taken care of - as per instructions mentioned above.
