### ISSUE TITLE
docker-opx image not found

### ISSUE THREAD

**Issue by maheshaka** [open-switch/opx-docs#3]
Hi,

I am trying to build OPX by following the steps mentioned in the below link:
https://github.com/open-switch/opx-docs/wiki/OpenSwitch-build-system

With the "opx_setup" I am getting the following error. Could you point me to what I am missing or doing wrong here?
**PS: I am able to resolve deb.debian.org and security.debian.org from outside the docker.**

Thanks
Mahesh
./opx_setup 
Sending build context to Docker daemon 132.1 kB
Step 1 : FROM debian:jessie
 ---> 62a932a5c143
Step 2 : MAINTAINER ops-dev@lists.openswitch.net
 ---> Using cache
 ---> 38bb22047ce3
Step 3 : RUN apt-get update && apt-get upgrade -y && apt-get install -y     dh-autoreconf     dh-systemd     git-buildpackage     lsb-release     vim     wget  && rm -rf /var/lib/apt/lists/*
 ---> Running in 70a84014d85c
Err http://deb.debian.org jessie InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Could not resolve 'deb.debian.org'
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Could not resolve 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'deb.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'deb.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dh-autoreconf
E: Unable to locate package dh-systemd
E: Unable to locate package git-buildpackage
E: Unable to locate package lsb-release
E: Unable to locate package vim
E: Unable to locate package wget
The command '/bin/sh -c apt-get update && apt-get upgrade -y && apt-get install -y     dh-autoreconf     dh-systemd     git-buildpackage     lsb-release     vim     wget  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Unable to find image 'docker-opx:base' locally
Pulling repository docker.io/library/docker-opx
docker: Error: image library/docker-opx:base not found.
See 'docker run --help'.
cat: id: No such file or directory
Error response from daemon: No such container: docker-opx:latest
cat: id: No such file or directory
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
Error response from daemon: No such image: docker-opx:base
OPX Docker Image
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@mahesh-VirtualBox:/home/mahesh/opx/opx-build/scripts# docker image docker-opx
docker: 'image' is not a docker command.
See 'docker --help'.
root@mahesh-VirtualBox:/home/mahesh/opx/opx-build/scripts# docker search docker-opx
NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED

Thanks
Mahesh

**Comment by jeff-yin** [comment]
This issue has been resolved, please review the new documentation and try again
