### ISSUE TITLE
can not enable L3 routing on S4248FBL-ON by simply following the L3 section

### ISSUE THREAD

**Issue by tmshlvck** [open-switch/opx-docs#31]
I might be missing some point in the OPX setup & config for L3 routing, but I can't make OPX to forward packets on Dell EMC S4248FBL-ON. After plain installation of OPX 3.1 I set

```
ip link set up dev e101-040-0
ip link set up dev e101-001-0
ip addr add 192.168.1.1/24 dev e101-040-0
ip addr add 192.168.2.1/24 dev e101-001-0
```

For the L3 test I have hosts with IP addresses 192.168.1.2 & 192.168.2.2 connected to the corresponding interfaces. The hosts (.2) can not ping the switch (.1) addresses. It seems switch can send out IMCP echo requests to the hosts, hosts are sending replies, but they never arrive to the Linux IP stack on the switch. And when I add routes to the hosts to use the .1 as a gateway for the other network it does not work as well. But ARP is working fine - I can see all the right records in ARP tables on the switch and on the hosts as well.

Both interfaces are up and running and there seems to be no L1/2 issue - I successfully tested L2 switching in the same physical setup beforehand.

If there is some simple step that I missed I suggest extending the L3 routing section of this manual with it.

**Comment by disaster123** [comment]
No you don’t miss anything there is a kernel driver missing in opx for this switch but nobody cares since dell switched their resources to sonic.

**Comment by mikelazar** [comment]
@disaster123 There's been an org change in OPX, but we are starting to look again at issues and fixes.

**Comment by gunasekaran-t** [comment]
@tmshlvck we have published the latest package with the fix. Please do `apt-get dist-upgrade` to get the latest package and reboot.

**Comment by tmshlvck** [comment]
Great! Works for me! Thanks!
