### ISSUE TITLE
Managing FDB

### ISSUE THREAD

**Issue by krishz11** [open-switch/opx-docs#4]
I am trying to do a traffic forwarding test (snake test). For this i need to create various VLAN's and maintain a FDB. I am creating bridges using 'brctl' command and adding interfaces to it and able to do this fine. By using 'bridge' command trying to create a FDB but traffic forward is not happening and i am not sure whether the entries created is correct or not. In the below link (https://github.com/open-switch/opx-docs/wiki/Layer-2) it mentioned as there is no linux command support to manage MAC FDB's.

So now trying to access SAI libraries (libopx_sai_common.so) from Python(using ctypes) and still not succeeded in this. 

Please kindly explain the steps to do a snake test / how to create/manage a FDB entry (command line or any application)

**Comment by jeff-yin** [comment]
Had a similar question on the OPX Rocket Chat. Selectively pasting the conversation here:

1) cps_config_mac.py, cps_config_vlan.py : these two utilities can be used for VLAN and MAC configuration. Both of them have usage details e.g. root@OPX:~# cps_config_vlan.py
< Usage >
cps_config_vlan can be used to configure the VLAN and ports for VLAN

-h, --help: Show the option and usage
-a, --add : Add VLAN to the configuration
-d, --del : Delete the specific VLAN
-i, --id : VLAN ID user want to operate on
-p, --port: port(s) that need to be added for a VLAN
-m, --mac : mac address that need to configured for the given VLAN
--ifdex : ifIndex of the VLAN that is configured previously
--addport : option to add port to the given VLAN
--addmac : add a mac address to the VLAN
-s, --show: show the VLAN parameter, when no VLAN ID given show all
-t, --tagged: If user want to add the port as tagged port, default untagged

--vlantype : Type of vlan (data<1>/management<2>)
Example:
cps_config_vlan.py --add --id 100 --vlantype 1 --port e101-001-0,e101-004-0
cps_config_vlan.py --del --name br100
cps_config_vlan.py --addport --name br100 --port e101-001-0,e101-004-0
cps_config_vlan.py --addmac --name br100 --mac 90:b1:1c:f4:a8:b1
cps_config_vlan.py --show [--name br100]

Here is the config guide for OPX : http://archive.openswitch.net/docs/2.1.0/openswitch_opx_config_guide_r210.pdf
