### ISSUE TITLE
open-switch and p4 on DELL S4048

### ISSUE THREAD

**Issue by dkalog** [open-switch/opx-docs#6]
Hi *,
I would like to  install a p4 capability on an  opx  binary for DELL switch . Is the 
https://github.com/open-switch/ops-switchd-p4switch-plugin correct approach ?

Cheers,
Dimitriss

**Comment by jeff-yin** [comment]
Hi Dimitriss,

Unfortunately no. That's an OPS repo, and the OPS project has been deprecated since HP left the program. P4 on OPX is going to take some development effort, and I don't personally know of any people working on that at the moment.

Thanks for reaching out!
Jeff
