### ISSUE TITLE
vagrant setup

### ISSUE THREAD

**Issue by dkalog** [open-switch/opx-docs#7]
Hi *,

I have picked up opx/2.2.0-dev  from the vagrant store. Do you know which architecture corresponds to ? I have used the following Vagrant file
------------------------
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    # Configure switch, i.e., device under test (DUT)
    config.vm.define "switch" do |switch|
        switch.vm.box = "opx/2.2.0-dev"

        switch.vm.network "private_network", ip: "172.16.0.10", netmask: "255.255.255.0", virtualbox__intnet: "gen-sw"
        switch.vm.network "private_network", ip: "172.16.0.11", netmask: "255.255.255.0", virtualbox__intnet: "sw-rcv"
        switch.vm.network "private_network", ip: "192.168.50.4"

        switch.vm.provider "virtualbox" do |virtualbox|
            # Customize the amount of memory on the VM:
            virtualbox.memory = "1024"
            virtualbox.cpus = "1"
            # Enable promiscuous mode
            virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            virtualbox.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        end

end
-------------
which successfully executes boots up. This VM  is not a S 6000  emulated switch though. 
How can I find to which architecture corresponds to ?
What are the HW framework  of the VMs in the vagrant store ?

Cheers,
Dimitris

**Comment by jghalam** [comment]
You can use "opx-show-version” command to see the platform type.

vagrant@opx22_vm:~$ opx-show-version
OS_NAME="OPX"
OS_VERSION="2.2.0"
PLATFORM="S6000-VM"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.2.0.0-dev"
BUILD_DATE="2017-10-27T22:22:51+0000"
INSTALL_DATE="2018-01-11T23:37:31+0000"
Failed to get D-Bus connection: No such file or directory
SYSTEM_STATE= 
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no
vagrant@opx22_vm:~$

**Comment by jeff-yin** [comment]
@dkalog do you need more assistance with this?
To add to the above message, make sure you run opx-* commands as sudo/root, otherwise you will get those "Failed to get D-Bus connection" errors.

**Comment by jeff-yin** [comment]
I'm going to close the issue for now, please feel free to reopen if you still have questions surrounding this.
