### ISSUE TITLE
Bond interface CPS API examples

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-docs#8]
The Interfaces wiki page states that there are CPS API examples for configuring Port-channel (LAG) bond interfaces (https://github.com/open-switch/opx-docs/wiki/Interfaces#delete-bond-interface) 

I have not been able to find such an example.

Does such an example exist?
If not, is it currently possible to do the configuration shown in the Interfaces wiki page via the CPS API?

**Comment by jeff-yin** [comment]
Hi @james-jra , there are instructions on how to configure a port-channel interface in the OPX config guide (https://archive.openswitch.net/docs/2.1.0/openswitch_opx_config_guide_r210.pdf)

It is also doable via CPS, but I think we're missing the application example from the wiki. We need to add it to https://github.com/open-switch/opx-docs/wiki/Programming-examples

**Comment by james-jra** [comment]
Great, after some searching, I also found the following script in the opx-nas-interface repository which should provide the insight I need (https://github.com/open-switch/opx-nas-interface/blob/master/scripts/bin/cps_config_lag.py)

Thanks
