### ISSUE TITLE
VM instructions install older VM

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-docs#9]
Trying to install the OPX VM v2.2, I got the installer from https://archive.openswitch.net/vm-tools/2.2.0/lvm as suggested by https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine.

Despite the URL, it installed VM 2.1, and gave no warning that it was doing so.

**Comment by jeff-yin** [comment]
Currently working on this. In short, we're going to get rid of this unnecessary coupling between vm-tools and OPX versions. By default, if a --bin argument is not specified, the vm-tools will now install from http://archive.openswitch.net/installers/stable/Dell-EMC/PKGS_OPX-stable-installer-x86_64.bin 

Of course, there will still be the option to specify a particular OPX installer image via the --bin argument.

**Comment by jeff-yin** [comment]
This issue will be closed once the above is implemented and our documentation is updated.

**Comment by jeff-yin** [comment]
Done.
